### ISSUE TITLE
Cannot build 'Blazor.FlexGrid.Demo.Serverside'

### ISSUE THREAD

**Issue by BartWally** [Mewriick/Blazor.FlexGrid#46]
Hi,

I try to migrate my Blazor Server-Side project with Blazor-Flexgrid to the newest version (.Net Core 3.0 prev3).
I noticed that your demo project is not finished. Are you planing to support Server-Side mode in your examples projects? Currently the demo is detached from solution and cannot be build because of error:

https://github.com/Mewriick/Blazor.FlexGrid/blob/3bc32d468bc27e012d33878ed31ee9ccf291384a/demo/Blazor.FlexGrid.Demo.Serverside/Startup.cs#L33

Chears!

**Comment by Mewriick** [comment]
Hello,

I still want to support Blazor Server-Side project . I must to delete the old one project and push updated version. But I have several issues with styles in server side. Also some Http services in IoC are no longer useful in server side project and I have to update docs how to register properly services for proper working of FlexGrid. 

I hope this week I fix this issues.

**Comment by Mewriick** [comment]
Hello, 
I add new Server Side project and updated README. Styles issues I solved by add refenreces required css files into head tag. I have to check it out why this is not included just with FlexGrid project automatically. For now you have at least demo project

**Comment by wally666** [comment]
Thx @Mewriick ! Do you think it is possible to use server side with "_framework/components.server.js" instead of "_framework/components.webassembly.js"? On MSDN I can see a small cross next to "components.server.js script†". Are they going to abandon the lighter version of server-side hosting model and only WebAssembly will be supported?

https://docs.microsoft.com/en-US/aspnet/core/razor-components/hosting-models?view=aspnetcore-3.0#server-side-hosting-model

Cheers!

**Comment by Mewriick** [comment]
@wally666 I do not think that they abadon lighter version, and WebAssemble will be only supported. According this release notes https://devblogs.microsoft.com/aspnet/blazor-0-8-0-experimental-release-now-available/ in Blazor 0.8.0 with Razor components application is running on ASP NET Core server and communicate with SignalR. 

I am actually little bit too confused about these hosting models.

I Also think that your link is outdated because extensions `app.UseServerSideBlazor<App.Startup>();` and `services.AddServerSideBlazor<App.Startup>();` is not used anymore I think
