### ISSUE TITLE
Bindable page size

### ISSUE THREAD

**Issue by Joebu** [Mewriick/Blazor.FlexGrid#76]
Is there a way to change the page size with binding so I can have a drop down with different options

**Comment by Mewriick** [comment]
Hello @Joebu 

you mean that you have separate dropdown component with numubers which is connected to the page size of the grid?

**Comment by Joebu** [comment]
correct


`<select @bind="@PageSize">
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
    </select>
<GridView
    PageSize="@PageSize"></GridView>`

**Comment by Mewriick** [comment]
@Joebu 

There is problem this can be done only for the first time when you create the grid because, after the paramteres are set and `TableDataSet` object is created, every parameter change is not applicated. I will think how to do this works for these kind of scenarios. Whole problem is in `OnParametersSetAsync` method which have some checks which not affect grid

**Comment by Mewriick** [comment]
@Joebu 

Version 0.11.0 contains new feature and will help solve your problem. See the [wiki](https://github.com/Mewriick/Blazor.FlexGrid/wiki/Triggers)
